### ISSUE TITLE
How to custom the Button's  text-color by theming?

### ISSUE THREAD

**Issue by Thammawat** [atanasster/grommet-nextjs#1]

**Comment by atanasster** [comment]
Hi, you can set the text color in the theme:
```
button: {
  colors: {
    text: xxx
  }
}
```

**Comment by Thammawat** [comment]
Yeahhh. Thank you It's  work.Amm... it can set Button's text-color in normal <Button> but how about to set text-color in <Button primary>?

**Comment by atanasster** [comment]
If you mean the color on dark background, you cant currently

**Comment by Thammawat** [comment]
Sorry for my last comment my question is  how about to set text-color in primary button?

**Comment by atanasster** [comment]
np, was trying to guess the question :)

You cant directly change the text color for primary. You can change the background ex `<Button color='accent-2' primary={true} label='Submit' onClick={() => {}} />`
but the text color is taken from the global dark/light text colors `global.colors.darkBackground.text` and `global.colors.lightBackground.text` 

Since the default `brand` color is treated as `dark`, you can change `global.colors.darkBackground.text`  
```
<Button theme={{ global: { colors: { darkBackground: { text: 'red' } } } }} primary={true} label='Submit' onClick={() => {}} />
```

**Comment by Thammawat** [comment]
Thank you vary much.
