### ISSUE TITLE
Spinning - color prop

### ISSUE THREAD

**Issue by stelian87** [atanasster/grommet-nextjs#14]
Hi,
The color prop doesn't seem to work properly. If I specify the color the spinner becomes a light grey.
This can be seen on your page as well: 
https://grommet-nextjs.herokuapp.com/examples/grommet-controls/Spinning/color?theme=grommet-v1

Thanks

**Comment by atanasster** [comment]
Thanks a lot for reporting it, fixed in 1.1.10 and also updated the web site - please upgrade grommet-controls. 
Even before, the color wasn't updatable on all of the spinners, let me know if your are using one the the last 3 spinners and need to change its color.

I really appreciate you taking the time to file issues, but would it be possible to file issues in the grommet-controls github repo (the current one is for the web site): https://github.com/atanasster/grommet-controls

**Comment by stelian87** [comment]
@atanasster Will definitely do that from now on. Thanks a bundle!

**Comment by atanasster** [comment]
Thank you
